### ISSUE TITLE
lightriders slows to a crawl

### ISSUE THREAD

**Issue by weshardee** [jmerle/ai-bot-workspace#10]
When running the lightriders game for games of longer than 40 turns, the performance of the visualization degrades significantly to the point that it's actually much faster to pause the game and then manually click the forward button to watch the results.

running on MacOS 10.13.4

**Comment by jmerle** [comment]
Weird, I do not have that problem on Ubuntu 18.04. Does the problem also occur if you close some other applications (i.e. could it have to do with a shortage of memory or cpu)?

**Comment by jmerle** [comment]
Please re-open the issue with more information if the issue still occurs.
