### ISSUE TITLE
[UBUNTU] Error PATH

### ISSUE THREAD

**Issue by SunD004** [jmerle/ai-bot-workspace#13]
## Current behavior
What is the current situation?

Error
The match failed to run. Make sure the paths to the bot are correctly set (File -> Settings) and try again.

## Expected behavior
What do you expect to happen?

Run match 

## Steps to reproduce
How to reproduce the issue?

Set the path of the bot :

node ./home/sund/cryptotrader-starterbot-javascript/main.js -> don't work
node ./home/sund/cryptotrader-starterbot-javascript/ -> don't work
node ./cryptotrader-starterbot-javascript/main.js -> don't work
node ./cryptotrader-starterbot-javascript/ -> don't work

## Extra information
OS:  
UBUNTU 18
AI Bot Workspace version: 
v2.4.3

**Comment by jmerle** [comment]
Riddles.io no longer exists and because of that this project is no longer being maintained.
